from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from utils.db import get_db
from utils.pdf_extractor import extract_text_from_pdf
from utils.auth_helpers import allowed_file
from werkzeug.utils import secure_filename
from datetime import datetime
import os

report_bp = Blueprint("report", __name__)

def _ai_compare_summary(text1: str, text2: str) -> str:
    """Use OpenAI to generate a structured medical comparison summary."""
    try:
        from openai import OpenAI
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise Exception("No API key")
        client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {
                    "role": "system",
                    "content": """You are a medical report analyzer. Compare the two medical reports provided and generate a structured AI Health Summary with these exact sections:

⚠️ Disclaimer: This analysis is generated by AI and should not be considered as a replacement for professional medical advice. Please consult with a healthcare provider for proper medical diagnosis and treatment.

**AI Generated Diagnosis:**

**Potential Health Risks:**
List each risk with: Name: Risk level - Explanation of the finding and what it means.

**Changes Since Previous Report:**
Highlight what improved, what worsened, and what stayed the same.

**Recommendations:**
List actionable recommendations based on the comparison.

**Urgency of Medical Consultation:**
State whether immediate, routine, or no consultation is needed and why.

Keep it clear, structured, and medically accurate."""
                },
                {
                    "role": "user",
                    "content": f"Previous Report:\n{text1[:2000]}\n\nCurrent Report:\n{text2[:2000]}\n\nGenerate the AI Health Summary comparing these two reports."
                }
            ],
            temperature=0.4,
            max_tokens=1500
        )
        return response.choices[0].message.content
    except Exception as e:
        return _fallback_summary(text1, text2)


def _fallback_summary(text1: str, text2: str) -> str:
    """Rule-based summary when AI is unavailable."""
    import re

    def extract_numbers(text):
        return re.findall(r'(\w[\w\s]*?):\s*([\d.]+)\s*(mg/dL|g/dL|%|mmHg|U/L|mEq/L)?', text)

    vals1 = {m[0].strip().lower(): m[1] for m in extract_numbers(text1)}
    vals2 = {m[0].strip().lower(): m[1] for m in extract_numbers(text2)}

    changes = []
    for key in vals2:
        if key in vals1 and vals1[key] != vals2[key]:
            try:
                diff = float(vals2[key]) - float(vals1[key])
                direction = "increased" if diff > 0 else "decreased"
                changes.append(f"• {key.title()}: {vals1[key]} → {vals2[key]} ({direction})")
            except Exception:
                pass

    summary = "⚠️ Disclaimer: This analysis is generated by AI and should not be considered as a replacement for professional medical advice.\n\n"
    summary += "**AI Generated Diagnosis:**\n\n"
    summary += "**Changes Since Previous Report:**\n"
    if changes:
        summary += "\n".join(changes)
    else:
        summary += "• No significant numeric changes detected between reports."
    summary += "\n\n**Recommendations:**\n• Consult your healthcare provider to review these results.\n• Continue regular health monitoring.\n• Maintain a healthy lifestyle with balanced diet and exercise.\n\n"
    summary += "**Urgency of Medical Consultation:**\nRoutine check-up recommended. No immediate emergency detected based on available data."
    return summary

@report_bp.route("/upload", methods=["POST"])
@jwt_required()
def upload_report():
    user_id = get_jwt_identity()
    if "file" not in request.files:
        return jsonify({"error": "No file provided"}), 400

    file = request.files["file"]
    if not file.filename or not allowed_file(file.filename, "document"):
        return jsonify({"error": "Invalid file. Only PDF, DOC, DOCX allowed."}), 400

    filename = secure_filename(
        f"report_{user_id}_{datetime.utcnow().strftime('%Y%m%d%H%M%S')}_{file.filename}"
    )
    upload_dir = os.path.join(os.getenv("UPLOAD_FOLDER", "uploads"), "reports")
    os.makedirs(upload_dir, exist_ok=True)
    file_path = os.path.join(upload_dir, filename)
    file.save(file_path)

    # Extract text from PDF in memory only — not stored in DB
    extracted_text = ""
    if filename.lower().endswith(".pdf"):
        extraction = extract_text_from_pdf(file_path)
        if extraction.get("success"):
            extracted_text = extraction["text"]

    try:
        db = get_db()
        result = db.table("reports").insert({
            "user_id": user_id,
            "file_path": file_path,
            "created_at": datetime.utcnow().isoformat()
        }).execute()

        report = result.data[0]
        return jsonify({
            "message": "Report uploaded successfully",
            "report_id": report["report_id"],
            "file_path": file_path,
            "extracted_text": extracted_text[:500] + "..." if len(extracted_text) > 500 else extracted_text,
            "analysis": extracted_text[:300] if extracted_text else "Report saved. Upload a PDF to extract content."
        }), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@report_bp.route("/get", methods=["GET"])
@jwt_required()
def get_reports():
    user_id = get_jwt_identity()
    try:
        db = get_db()
        result = db.table("reports").select("report_id, file_path, created_at").eq("user_id", user_id).order("created_at", desc=True).execute()
        return jsonify({"reports": result.data or []}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@report_bp.route("/delete/<int:report_id>", methods=["DELETE"])
@jwt_required()
def delete_report(report_id):
    user_id = get_jwt_identity()
    try:
        db = get_db()
        result = db.table("reports").select("report_id, file_path").eq("report_id", report_id).eq("user_id", user_id).execute()
        if not result.data:
            return jsonify({"error": "Report not found"}), 404
        file_path = result.data[0].get("file_path")
        if file_path and os.path.exists(file_path):
            os.remove(file_path)
        db.table("reports").delete().eq("report_id", report_id).execute()
        return jsonify({"message": "Report deleted"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@report_bp.route("/compare", methods=["GET"])
@jwt_required()
def compare_two_reports():
    user_id = get_jwt_identity()
    report_id1 = request.args.get("report1")
    report_id2 = request.args.get("report2")

    if not report_id1 or not report_id2:
        return jsonify({"error": "Two report IDs required"}), 400

    try:
        db = get_db()
        r1 = db.table("reports").select("report_id, file_path").eq("report_id", report_id1).eq("user_id", user_id).execute()
        r2 = db.table("reports").select("report_id, file_path").eq("report_id", report_id2).eq("user_id", user_id).execute()

        if not r1.data or not r2.data:
            return jsonify({"error": "One or both reports not found"}), 404

        def read_text(row):
            path = row.get("file_path", "")
            if path.lower().endswith(".pdf") and os.path.exists(path):
                res = extract_text_from_pdf(path)
                return res.get("text", "") if res.get("success") else ""
            return ""

        text1 = read_text(r1.data[0])
        text2 = read_text(r2.data[0])

        # Generate structured AI health summary
        ai_summary = _ai_compare_summary(text1, text2)

        return jsonify({
            "ai_summary": ai_summary,
            "analysis1": text1[:800] if text1 else "No text extracted from previous report.",
            "analysis2": text2[:800] if text2 else "No text extracted from current report."
        }), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@report_bp.route("/translate/<int:report_id>", methods=["POST"])
@jwt_required()
def translate_report(report_id):
    user_id = get_jwt_identity()
    data = request.get_json() or {}
    target_language = data.get("language", "en")

    try:
        db = get_db()
        result = db.table("reports").select("report_id, file_path").eq("report_id", report_id).eq("user_id", user_id).execute()
        if not result.data:
            return jsonify({"error": "Report not found"}), 404

        path = result.data[0].get("file_path", "")
        text = ""
        if path.lower().endswith(".pdf") and os.path.exists(path):
            extraction = extract_text_from_pdf(path)
            text = extraction.get("text", "") if extraction.get("success") else ""

        translated = text
        try:
            from utils.translator import translator as tr
            if text and target_language != "en":
                translated = tr.translate_text(text[:2000], target_lang=target_language, source_lang="en")
        except Exception:
            pass

        return jsonify({
            "original": text[:600] if text else "No text available.",
            "translated": translated[:600] if translated else "Translation not available.",
            "language": target_language
        }), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500
